//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.wsDashboardSoap")]
    public interface wsDashboardSoap {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/documentActions", ReplyAction="*")]
        Win.WebService.documentActionsResponse documentActions(Win.WebService.documentActionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/documentActions", ReplyAction="*")]
        System.Threading.Tasks.Task<Win.WebService.documentActionsResponse> documentActionsAsync(Win.WebService.documentActionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentActionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentActions", Namespace="http://tempuri.org/", Order=0)]
        public Win.WebService.documentActionsRequestBody Body;
        
        public documentActionsRequest() {
        }
        
        public documentActionsRequest(Win.WebService.documentActionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class documentActionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public documentActionsRequestBody() {
        }
        
        public documentActionsRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentActionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentActionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Win.WebService.documentActionsResponseBody Body;
        
        public documentActionsResponse() {
        }
        
        public documentActionsResponse(Win.WebService.documentActionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class documentActionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object documentActionsResult;
        
        public documentActionsResponseBody() {
        }
        
        public documentActionsResponseBody(object documentActionsResult) {
            this.documentActionsResult = documentActionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsDashboardSoapChannel : Win.WebService.wsDashboardSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsDashboardSoapClient : System.ServiceModel.ClientBase<Win.WebService.wsDashboardSoap>, Win.WebService.wsDashboardSoap {
        
        public wsDashboardSoapClient() {
        }
        
        public wsDashboardSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsDashboardSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsDashboardSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsDashboardSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Win.WebService.documentActionsResponse Win.WebService.wsDashboardSoap.documentActions(Win.WebService.documentActionsRequest request) {
            return base.Channel.documentActions(request);
        }
        
        public object documentActions(string userId) {
            Win.WebService.documentActionsRequest inValue = new Win.WebService.documentActionsRequest();
            inValue.Body = new Win.WebService.documentActionsRequestBody();
            inValue.Body.userId = userId;
            Win.WebService.documentActionsResponse retVal = ((Win.WebService.wsDashboardSoap)(this)).documentActions(inValue);
            return retVal.Body.documentActionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Win.WebService.documentActionsResponse> Win.WebService.wsDashboardSoap.documentActionsAsync(Win.WebService.documentActionsRequest request) {
            return base.Channel.documentActionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Win.WebService.documentActionsResponse> documentActionsAsync(string userId) {
            Win.WebService.documentActionsRequest inValue = new Win.WebService.documentActionsRequest();
            inValue.Body = new Win.WebService.documentActionsRequestBody();
            inValue.Body.userId = userId;
            return ((Win.WebService.wsDashboardSoap)(this)).documentActionsAsync(inValue);
        }
    }
}
