using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Models;
using Models.Repository;

namespace Win.OB
{
    public partial class ucObligations : DevExpress.XtraEditors.XtraUserControl
    {
        public ucObligations()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            entityServerModeSource1.QueryableSource = new UnitOfWork().ObligationsRepo.Fetch();
        }

        private void btnNew_Click(object sender, EventArgs e)
        {
            frmAddEditObligation frm = new frmAddEditObligation(MethodType.Add, null);
            frm.ShowDialog();
            entityServerModeSource1.QueryableSource = new UnitOfWork().ObligationsRepo.Fetch();
        }

        private void ucObligations_Load(object sender, EventArgs e)
        {

        }

        private void btnDeleteRepoOBR_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {

        }
    }
}
