using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Helpers;
using Models;
using Models.Repository;

namespace DMS
{
    public partial class UCBox : DevExpress.XtraEditors.XtraUserControl
    {
        public UCBox()
        {
            InitializeComponent();

            Init();
            // This line of code is generated by Data Source Configuration Wizard
        }

        void Init()
        {
            try
            {
                UnitOfWork unitOfWork = new UnitOfWork(new DTSDb());
                this.BoxEntityServerModeSource.QueryableSource = unitOfWork.BoxesRepo.Fetch();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, ex.Message, MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        void Details(Boxes item)
        {
            try
            {
                UnitOfWork unitOfWork = new UnitOfWork(new DTSDb());
                this.FolderEntityServerModeSource.QueryableSource =
                    unitOfWork.FoldersRepo.Fetch(x => x.BoxId == item.Id);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, ex.Message, MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void BoxGridView_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (BoxGridView.GetRow(e.FocusedRowHandle) is Boxes item)
            {
                Details(item);
            }
        }

        private void txtSearch_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                Search(txtSearch.Text);
            }
        }

        void Search(string search)
        {
            try
            {
                UnitOfWork unitOfWork = new UnitOfWork(new DTSDb());


                var query = unitOfWork.BoxesRepo.Fetch(x => x.BoxName.Contains(search));
                this.BoxEntityServerModeSource.QueryableSource = query;
                Details(query.FirstOrDefault());
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, ex.Message, MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }
}
