//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_USER
    {
        public int USER_idx { get; set; }
        public string USER_nme { get; set; }
        public string USER_pwd { get; set; }
        public string USER_fnm { get; set; }
        public string USER_mnm { get; set; }
        public string USER_lnm { get; set; }
        public string USER_email { get; set; }
        public Nullable<bool> USER_sts { get; set; }
        public string USER_crd { get; set; }
        public string USER_mod { get; set; }
        public string USER_off { get; set; }
        public string USER_div { get; set; }
        public Nullable<bool> USER_adm { get; set; }
        public Nullable<bool> USER_reset { get; set; }
    }
}
