//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actions()
        {
            this.Actions1 = new HashSet<Actions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public string Category { get; set; }
        public string Value { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> OfficeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actions> Actions1 { get; set; }
        public virtual Actions Actions2 { get; set; }
    }
}
