//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIReports()
        {
            this.AIRDetails = new HashSet<AIRDetails>();
        }
    
        public int Id { get; set; }
        public string ControlNo { get; set; }
        public string Office { get; set; }
        public string Division { get; set; }
        public string Center { get; set; }
        public string Code { get; set; }
        public Nullable<int> RISNo { get; set; }
        public Nullable<int> SAINo { get; set; }
        public Nullable<System.DateTime> RISDate { get; set; }
        public Nullable<System.DateTime> SAIDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRDetails> AIRDetails { get; set; }
    }
}
