//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllotmentLetter
    {
        public int Id { get; set; }
        public Nullable<int> PRId { get; set; }
        public string Reason { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Letter { get; set; }
        public string HeadofDivision { get; set; }
        public string HeadofDivisionPOS { get; set; }
        public string PBO { get; set; }
        public string PBOPos { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AppropriationId { get; set; }
    
        public virtual Appropriations Appropriations { get; set; }
        public virtual PurchaseRequests PurchaseRequests { get; set; }
    }
}
