//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allotments
    {
        public int Id { get; set; }
        public Nullable<int> AppropriationId { get; set; }
        public Nullable<System.DateTime> AllotmentDate { get; set; }
        public Nullable<decimal> AllotmentAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedB { get; set; }
    
        public virtual Appropriations Appropriations { get; set; }
    }
}
