//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AOQ()
        {
            this.BacMembers = new HashSet<Signatories>();
            this.AOQDetails = new HashSet<AOQDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PRId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ControlNo { get; set; }
        public string Description { get; set; }
        public string Purpose { get; set; }
        public string NameofProject { get; set; }
        public string RequisitioningOffice { get; set; }
        public Nullable<decimal> ABC { get; set; }
        public Nullable<int> RFQNo { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedById { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string Head { get; set; }
        public string HeadPosition { get; set; }
        public Nullable<int> BACChairperson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signatories> BacMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AOQDetails> AOQDetails { get; set; }
        public virtual Signatories Signatories { get; set; }
        public virtual Offices Offices { get; set; }
        public virtual PurchaseRequests PurchaseRequests { get; set; }
    }
}
