//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appropriations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appropriations()
        {
            this.Allotments = new HashSet<Allotments>();
            this.SourceReAlignments = new HashSet<ReAlignments>();
            this.TargetReAlignments = new HashSet<ReAlignments>();
            this.AllotmentLetter = new HashSet<AllotmentLetter>();
            this.ORDetails = new HashSet<ORDetails>();
            this.PurchaseRequests = new HashSet<PurchaseRequests>();
        }
    
        public int Id { get; set; }
        public string AccountCode { get; set; }
        public string AccountCodeText { get; set; }
        public string FundType { get; set; }
        public Nullable<int> FundTypeId { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> Appropriation { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Createdby { get; set; }
        public Nullable<int> OfficeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allotments> Allotments { get; set; }
        public virtual FundTypes FundTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReAlignments> SourceReAlignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReAlignments> TargetReAlignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllotmentLetter> AllotmentLetter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDetails> ORDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequests> PurchaseRequests { get; set; }
    }
}
