//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_VHD
    {
        public long VHD_IDX { get; set; }
        public string VHD_VNO { get; set; }
        public string VHD_DESC { get; set; }
        public string VHD_RCTR { get; set; }
        public string VHD_FYR { get; set; }
        public string VHD_PART { get; set; }
        public Nullable<bool> VHD_DEL { get; set; }
        public string VHD_DBY { get; set; }
        public string VHD_ACCT { get; set; }
        public Nullable<bool> VHD_DIS { get; set; }
        public string VHD_REM { get; set; }
        public string VHD_PRD { get; set; }
        public string VHD_ITEM { get; set; }
        public string VHD_FUND { get; set; }
        public string VHD_PMOD { get; set; }
        public Nullable<decimal> VHD_NAMT { get; set; }
        public Nullable<bool> VHD_REV { get; set; }
        public string VHD_REF { get; set; }
        public string VHD_RBY { get; set; }
        public Nullable<System.DateTime> VHD_RDT { get; set; }
        public Nullable<bool> VHD_APP { get; set; }
        public string VHD_ABY { get; set; }
        public Nullable<System.DateTime> VHD_ADT { get; set; }
        public string VHD_UCR { get; set; }
        public Nullable<System.DateTime> VHD_CRD { get; set; }
        public string VHD_UMD { get; set; }
        public Nullable<System.DateTime> VHD_MOD { get; set; }
        public Nullable<System.DateTime> VHD_DTE { get; set; }
        public Nullable<decimal> VHD_AMT { get; set; }
        public string VHD_CNO { get; set; }
        public string VHD_CDE { get; set; }
        public string VHD_OBR { get; set; }
        public Nullable<bool> VHD_INI { get; set; }
        public string VHD_IBY { get; set; }
        public Nullable<System.DateTime> VHD_IDT { get; set; }
        public string VHD_CUST { get; set; }
        public string VHD_ACTION { get; set; }
        public string VHD_STATUS { get; set; }
        public string VHD_DIS2 { get; set; }
        public Nullable<bool> VHD_SHOW { get; set; }
        public Nullable<long> VHD_VHEAD { get; set; }
        public string VHD_REM2 { get; set; }
        public string VHD_SIGN { get; set; }
        public string VHD_POS { get; set; }
        public string VHD_BANK { get; set; }
        public string VHD_PAY { get; set; }
        public string VHD_NOTE { get; set; }
        public Nullable<bool> VHD_PRNT { get; set; }
        public string VHD_CTYPE { get; set; }
        public Nullable<bool> VHD_SCHK { get; set; }
        public string VHD_CHKNOTE { get; set; }
        public Nullable<bool> VHD_REL { get; set; }
        public string VHD_SIGN2 { get; set; }
        public string VHD_POS2 { get; set; }
        public string VHD_TRNO { get; set; }
        public string VHD_TRKN { get; set; }
        public string VHD_TYPE { get; set; }
        public Nullable<bool> VHD_PTO { get; set; }
        public string VHD_SOURCE { get; set; }
    }
}
