//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultAccounts
    {
        public int Id { get; set; }
        public string AccountCode { get; set; }
        public string AccountCodeText { get; set; }
        public string AccountName { get; set; }
        public string FundType { get; set; }
        public Nullable<int> FundTypeId { get; set; }
    
        public virtual FundTypes FundTypes { get; set; }
    }
}
