//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultSettings
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public string Department { get; set; }
        public string ChiefOfOffice { get; set; }
        public string ChiefOfOfficePos { get; set; }
        public string ResponsibilityCenter { get; set; }
        public string ResponsibilityCenterCode { get; set; }
        public string OfficeId { get; set; }
        public Nullable<bool> IsDepartment { get; set; }
        public string UnderOf { get; set; }
    }
}
