//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int Id { get; set; }
        public string ControlNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CommunicationType { get; set; }
        public string DocumentType { get; set; }
        public Nullable<int> SourceOfficeId { get; set; }
        public Nullable<int> Signatory { get; set; }
        public string SignatoryPosition { get; set; }
        public string Subject { get; set; }
        public Nullable<int> MainActivityId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> OfficeId { get; set; }
    }
}
