//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentActions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentActions()
        {
            this.DocumentActions1 = new HashSet<DocumentActions>();
            this.RoutedToUsers = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RefId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> MainActivityId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> SubActivityId { get; set; }
        public string Status { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string CreatedBy { get; set; }
        public string TableName { get; set; }
        public string Remarks { get; set; }
        public string EndorsedTo { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<bool> isSaved { get; set; }
        public string ControlNo { get; set; }
        public Nullable<bool> isDone { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string ObR_PR_No { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> RoutedToOfficeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentActions> DocumentActions1 { get; set; }
        public virtual DocumentActions DocumentActions2 { get; set; }
        public virtual Users CreatedByUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> RoutedToUsers { get; set; }
        public virtual Offices Offices { get; set; }
    }
}
