//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int Id { get; set; }
        public Nullable<int> RefId { get; set; }
        public string TableName { get; set; }
        public string Path { get; set; }
        public string RootFolder { get; set; }
        public string OriginalFileName { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
