//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folders
    {
        public int Id { get; set; }
        public string FolderName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BoxId { get; set; }
        public string FolderCode { get; set; }
    
        public virtual Boxes Boxes { get; set; }
    }
}
