//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItenaryDetails
    {
        public int Id { get; set; }
        public Nullable<int> IOTId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PlaceVisited { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public string MeansOfTransportation { get; set; }
        public string TransportationFee { get; set; }
        public Nullable<decimal> PerDiems { get; set; }
        public Nullable<decimal> DailyAllowance { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ItenaryofTravels ItenaryofTravels { get; set; }
    }
}
