//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Letters()
        {
            this.Obligations = new HashSet<Obligations>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RefId { get; set; }
        public string TableName { get; set; }
        public string ControlNo { get; set; }
        public string Template { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string InsideAddress { get; set; }
        public string Salutation { get; set; }
        public string Body { get; set; }
        public string Closing { get; set; }
        public string Signatories { get; set; }
        public string SignatoriesPosition { get; set; }
        public string CC { get; set; }
        public Nullable<bool> InTheAbsence { get; set; }
        public string Title { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obligations> Obligations { get; set; }
        public virtual Users Users { get; set; }
        public virtual Offices Offices { get; set; }
    }
}
