//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAR()
        {
            this.PARDetails = new HashSet<PARDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PRId { get; set; }
        public string EntityName { get; set; }
        public string FundCluster { get; set; }
        public Nullable<int> PGSOId { get; set; }
        public string PGSO { get; set; }
        public string PGSOPosition { get; set; }
        public Nullable<int> ReceivedById { get; set; }
        public string ReceivedBy { get; set; }
        public string ReceivedByPos { get; set; }
        public Nullable<int> IssuedById { get; set; }
        public string IssuedBy { get; set; }
        public string IssuedByPos { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual PurchaseRequests PurchaseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARDetails> PARDetails { get; set; }
    }
}
