//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollDifferentialDetails
    {
        public int Id { get; set; }
        public Nullable<int> PayrollDiffentialId { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Designation { get; set; }
        public string EmployeeName { get; set; }
        public string SalaryGrade { get; set; }
        public Nullable<decimal> NewRate { get; set; }
        public Nullable<decimal> OldRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> DiffMidYearBonus { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<decimal> DiffBonus { get; set; }
        public Nullable<decimal> PHPS { get; set; }
        public Nullable<decimal> PHGS { get; set; }
        public Nullable<decimal> PIPS { get; set; }
        public Nullable<decimal> PIGS { get; set; }
        public Nullable<decimal> GSISPS { get; set; }
        public Nullable<decimal> GSISGS { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual PayrollDifferentials PayrollDifferentials { get; set; }
    }
}
