//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayrollOT()
        {
            this.PayrollOTDetails = new HashSet<PayrollOTDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ObRId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public string ApprovedPosition { get; set; }
        public Nullable<int> HeadId { get; set; }
        public string HeadPosition { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> PAId { get; set; }
        public string PAPosition { get; set; }
        public Nullable<int> PTId { get; set; }
        public string PTPosition { get; set; }
        public string Description { get; set; }
    
        public virtual Obligations Obligations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollOTDetails> PayrollOTDetails { get; set; }
    }
}
