//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollDetails
    {
        public int Id { get; set; }
        public Nullable<int> PayrollId { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> ColumnTitle1 { get; set; }
        public Nullable<decimal> ColumnTitle2 { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Payrolls Payrolls { get; set; }
    }
}
