//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollOTDetails
    {
        public int Id { get; set; }
        public Nullable<int> PayrollOTId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> RatePerMonth { get; set; }
        public Nullable<decimal> RatePerDay { get; set; }
        public Nullable<decimal> RatePerHr { get; set; }
        public Nullable<decimal> WeekEndNoHrs { get; set; }
        public Nullable<decimal> WeekDayNoHrs { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> UnderPay { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ItemNo { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual PayrollOT PayrollOT { get; set; }
    }
}
