//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PIS()
        {
            this.PISDetails = new HashSet<PISDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PRId { get; set; }
        public Nullable<int> TransferorId { get; set; }
        public Nullable<int> TransfereeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PreparedBy { get; set; }
        public string PreparedByPos { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PISDetails> PISDetails { get; set; }
        public virtual PurchaseRequests PurchaseRequests { get; set; }
    }
}
