//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDetails
    {
        public int Id { get; set; }
        public Nullable<int> PRId { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Category { get; set; }
        public string Item { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string TableName { get; set; }
    
        public virtual PurchaseRequests PurchaseRequests { get; set; }
    }
}
