//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseRequests()
        {
            this.AIReports = new HashSet<AIReports>();
            this.AllotmentLetter = new HashSet<AllotmentLetter>();
            this.AOQ = new HashSet<AOQ>();
            this.APRs = new HashSet<APRs>();
            this.Obligations = new HashSet<Obligations>();
            this.PIS = new HashSet<PIS>();
            this.PRDetails = new HashSet<PRDetails>();
            this.PriceQuotations = new HashSet<PriceQuotations>();
            this.PurchaseOrders = new HashSet<PurchaseOrders>();
            this.PAR = new HashSet<PAR>();
            this.ICS = new HashSet<ICS>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AppropriationId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ControlNo { get; set; }
        public string Description { get; set; }
        public string Purpose { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string TableName { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string PA { get; set; }
        public string PAPos { get; set; }
        public string DeptHead { get; set; }
        public string DeptHeadPos { get; set; }
        public string DivisionHead { get; set; }
        public string DivisionHeadPos { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsEarmark { get; set; }
        public string BudgetControlNo { get; set; }
        public bool IsClosed { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string CancellationReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIReports> AIReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllotmentLetter> AllotmentLetter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AOQ> AOQ { get; set; }
        public virtual Appropriations Appropriations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APRs> APRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obligations> Obligations { get; set; }
        public virtual Offices Offices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIS> PIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRDetails> PRDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceQuotations> PriceQuotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrders> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAR> PAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS> ICS { get; set; }
    }
}
