//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RISHeader()
        {
            this.RISDetails = new HashSet<RISDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PRId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string RISNo { get; set; }
        public string SAI { get; set; }
        public Nullable<System.DateTime> RISDate { get; set; }
        public Nullable<System.DateTime> SAIDate { get; set; }
        public string CreatedBy { get; set; }
        public string RequestedBy { get; set; }
        public string RequestedByPos { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedByPos { get; set; }
        public string IssuedBy { get; set; }
        public string IssuedByPos { get; set; }
        public string ReceivedBy { get; set; }
        public string ReceivedByPos { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Purpose { get; set; }
    
        public virtual Offices Offices { get; set; }
        public virtual PurchaseRequests PurchaseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISDetails> RISDetails { get; set; }
    }
}
