//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySchedules
    {
        public int Id { get; set; }
        public string SG { get; set; }
        public Nullable<int> Step { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
