//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signatories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Signatories()
        {
            this.BACMembers = new HashSet<AOQ>();
            this.BACChairperson = new HashSet<AOQ>();
            this.Liquidations = new HashSet<Liquidations>();
            this.Liquidations1 = new HashSet<Liquidations>();
        }
    
        public int Id { get; set; }
        public string Person { get; set; }
        public string Position { get; set; }
        public string Note { get; set; }
        public Nullable<int> Year { get; set; }
        public string Office { get; set; }
        public Nullable<bool> IsBacMember { get; set; }
        public string BacPosition { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AOQ> BACMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AOQ> BACChairperson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liquidations> Liquidations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liquidations> Liquidations1 { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
