//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signatories
    {
        public int Id { get; set; }
        public string Person { get; set; }
        public string Position { get; set; }
        public string Note { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
