//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrashBin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrashBin()
        {
            this.TrashBin1 = new HashSet<TrashBin>();
        }
    
        public int Id { get; set; }
        public string TableName { get; set; }
        public string OldValues { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Description { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> OfficeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrashBin> TrashBin1 { get; set; }
        public virtual TrashBin TrashBin2 { get; set; }
        public virtual Offices Offices { get; set; }
    }
}
