using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Models;
using Win.BL;

namespace Win.PO
{
    public partial class UCPO : DevExpress.XtraEditors.XtraUserControl
    {
        public UCPO(PurchaseRequests purchaseRequests)
        {
            InitializeComponent();
            LoadAddEditPO loadAddEditPO = new LoadAddEditPO(this, purchaseRequests);
            ((ILoad<PurchaseOrders>)loadAddEditPO).Init();
            // This line of code is generated by Data Source Configuration Wizard
        }
    }
}
