using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace Win.PO
{
    public partial class UCPO : DevExpress.XtraEditors.XtraUserControl
    {
        public UCPO()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }
    }
}
